
@begin

actor usuario as u

u -> (Visualiza dashboard)
u -> (Cria post-it simples)
u -> (Cria post-it de tarefas)
u -> (Arquiva post-it)
u -> (Visualiza post-its arquivados)
u -> (Busca post-it)

@end

